name: Checkmarx One Scan
on: 
  push:
    branches:
      - test

jobs:
  run-action:
    permissions:
      security-events: write
      contents: read
      pull-requests: write
      statuses: write
    runs-on: ubuntu
    steps:
      - name: Fetch Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
  
      - name: Scan with CxOne++ Action
        id: scan
        uses: checkmarx-ts/cxone-plusplus-github-action@master
        with:
          cx-tenant: cx_ps_nathan_leach
          cx-client-id: ${{ secrets.CX_CLIENT_ID }}
          cx-client-secret: ${{ secrets.CX_CLIENT_SECRET }}
          cx-cli-debug: false
          additional-scan-params: --file-include=*.jsx
          # build-container-tag: node:22
          attach-sarif-file: false
          upload-sarif-file: false
          attach-sbom-file: false

      - name: Display outputs
        shell: bash
        run: |
          echo "Scan ID: ${{ steps.scan.outputs.scan-id }}"
          echo "Project ID: ${{ steps.scan.outputs.project-id }}"
          echo "Scan Link: ${{ steps.scan.outputs.project-deeplink }}"
        

