name: Execute on GitHub Hosted Runner
on: 
  push:
  pull_request:

jobs:
  run-action:
    permissions:
      security-events: write
      contents: read
    runs-on: ubuntu-latest
    steps:
     
      - name: Fetch Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
  
      - name: Test CxOne++
        id: scan
        uses: nleach-test/cxone-plusplus-github-action@master
        with:
          cx-tenant: cx_ps_nathan_leach
          cx-client-id: ${{ secrets.CX_CLIENT_ID }}
          cx-client-secret: ${{ secrets.CX_CLIENT_SECRET }}
          cx-cli-debug: false
          additional-scan-params: --file-include=*.jsx
          build-container-tag: node:22-alpine
          attach-sarif-file: true
          upload-sarif-file: true
          attach-sbom-file: true

      - name: Display outputs
        shell: bash
        run: |
          echo "Scan ID: ${{ steps.scan.outputs.scan-id }}"
          echo "Project ID: ${{ steps.scan.outputs.project-id }}"
          echo "Scan Link: ${{ steps.scan.outputs.project-deeplink }}"
        
          
          
          
          
          

    
          
